### ISSUE TITLE
Error: Please update TS Conf.

### ISSUE THREAD

**Issue by inpos** [HackerVBI/ZiFi#2]
Получил сегодня модуль ZIFI от Tetroid-а.
Две недели назад обновил прошивку ZX Evo до последней с двойной конфигурацией из репозитория TSLabs.
Установил модуль, скачал последнюю версию ZIFI.spg, прописал настройки AP и времени в конфиг.
Запускаю и получаю:
`Error: Please update TS Conf.`
С зажатым Пробелом - то же самое.

**Comment by inpos** [comment]
За этот вывод в zifi.asm, как я понимаю, отвечает это блок:
```

		ld      bc,0xc7ef
		ld      de,0xfff1
		out     (c),e           ;Set API mode 1
		out     (c),d           ;Get Version
		in      a,(c)
		cp      0xff
		jp      z,nozifi
```
Т.е., если после отправки в порт 51183 последовательно 241 и 255, а при последующем чтении из этого порта получим 255, что прыгаем на nozifi.
Но из Basic 128 я сделал следующее:
```
out 51183, 241
out 51183, 255
print in 51183
```
в результате получил 1.
Если сброситься и до out-ов сделать print in 51183, то получаю 255.
Т.е. сам модуль отвечает после `Set API mode 1` и `Get Version` единицей.
Почему же тогда происходит прыжок на nozifi ?
Или исходник zifi.asm не соответствует скомпиленной версии ZIFI.spg ?

**Comment by HackerVBI** [comment]
Неожиданное поведение.
Надо узнать у разработчика, почему проверка отдаёт другой результат
Вы сможете пропатчить или перекомпилировать версию, убрав проверку?
обнулите три байта "jp      z,nozifi"

ещё вариант - прошить более старую прошивку тсконф

**Comment by inpos** [comment]
Я запросил у Tetroid версии тсконф и ZIFI.spg, на которых производилось тестирование модуля.
Он прислал мне свои файлы ZIFI.spg и zxevo_fw.bin.
После прошивки на присланную версию zxevo_fw.bin всё завелось.
Сейчас я ожидаю от Tetroid-а наименование версии zxevo_fw.bin, чтобы указать здесь.
Однако получается, что последняя версия zxevo_fw.bin не подходит?
Если это так, то это печально, т.к. в [этой инструкции](http://forum.tslabs.info/viewtopic.php?f=12&t=189) указаны ссылки именно на последнюю версию zxevo_fw.bin.

**Comment by inpos** [comment]
Рабочая версия из TS-BIOS от 11.10.2019 01:51:09

**Comment by HackerVBI** [comment]
Спасибо. 
Сбросил ссылку на это обсуждение TSLabs

**Comment by inpos** [comment]
Благодарю.

**Comment by inpos** [comment]
Я перепутал и ввёл в заблуждение Вас.
Команды в Basic 128 я делал на BaseConf (т.к. не помню, как в TS Conf переходить в этот бейсик из WC).
Скорее всего в последней версии TS Conf, в её бэйсике произошла бы та же самая ситуация с возвратом 255.
